name: Publish to Docker Hub

on:
  push:
    branches:
      - master
    tags:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          yozik04/nibe-mqtt
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: yozik04
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build
      uses: docker/bake-action@v2
      with:
        files: |
          ./docker/docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: build
        push: true